"""empty message

Revision ID: 8ee7b64e5630
Revises: 3d83447af70f
Create Date: 2020-10-29 14:38:47.237600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee7b64e5630'
down_revision = '3d83447af70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('start_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'start_time')
    # ### end Alembic commands ###
