"""empty message

Revision ID: 99353ef81904
Revises: 8ee7b64e5630
Create Date: 2020-10-29 14:54:01.844838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99353ef81904'
down_revision = '8ee7b64e5630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
